# Generated by Django 4.2.4 on 2023-08-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0005_movieratingslist_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieratingslist',
            name='movie_id',
            field=models.IntegerField(),
        ),
    ]
