# Generated by Django 4.2.4 on 2023-08-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0007_delete_movieratingslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRatingsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('poster_path', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
