# Generated by Django 4.2.4 on 2023-08-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0009_alter_movieratingslist_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieratingslist',
            name='account_id',
            field=models.IntegerField(default=0),
        ),
    ]
