# Generated by Django 4.2.4 on 2023-08-31 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0011_alter_account_email_alter_account_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieratingslist',
            name='account_id',
        ),
    ]
